# Generated by Django 4.1.4 on 2023-03-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/color2')),
            ],
        ),
        migrations.CreateModel(
            name='Color3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/color3')),
            ],
        ),
        migrations.AlterField(
            model_name='color1',
            name='image',
            field=models.ImageField(upload_to='images/color1/'),
        ),
    ]
