# Generated by Django 4.1.4 on 2023-03-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0011_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('roll', models.IntegerField()),
            ],
        ),
    ]
