# Generated by Django 4.1.4 on 2023-03-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0012_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
