# Generated by Django 4.1.4 on 2023-03-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0014_profile_bio_profile_gender_profile_social_url_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='u',
        # ),
    ]
