# Generated by Django 4.1.4 on 2023-03-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0015_remove_profile_u'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_url',
        ),
    ]
